### ISSUE TITLE
Задача для Андрея

### ISSUE THREAD

**Issue by tiranderel** [tiranderel/DataBase#3]
Привет, начинаем делать проект по информатике! Твоя задача написать две программы (серверную и клиентскую). Серверная программа стоит на компьютере, от которого мы знаем IP адрес. Клиентское приложение по Socket соединяется с серверным, отправляет ему строку (любую). Сервер её получает, отправляет ответ (например, получено/ошибка/какое-то число) и отсоединяется. Клиент получает ответ. Задача сложновата, но в интернете про Socket много информации, так что если возникнут проблемы, то сразу же пиши!

**Comment by assert2** [comment]
дело сделано
